CREATE TABLE QUIZ(
    ID SERIAL ,
    QUESTION TEXT NOT NULL,
    ANSWER BOOLEAN NOT NULL,
    AUTHOR CHARACTER VARYING(20) NOT NULL
    PRIMARY KEY(ID)
);

COMMENT ON COLUMN QUIZ.ID IS 'クイズ情報を識別するID';
COMMENT ON COLUMN QUIZ.QUESTION IS 'クイズの内容';
COMMENT ON COLUMN QUIZ.ANSWER IS 'クイズの回答';
COMMENT ON COLUMN QUIZ.AUTHOR IS '作成者';